### PR TITLE
Fix build emulation for multi-stage builds

### LINKED ISSUE #814: Multi-stage emulated build fails
- **resin-cli version:**
  - 7.0.3
- **Operating system and architecture:**
  - build: linux/amd64
  - target: armv7hf

I'm trying to make use of the multi-stage build feature in recent Docker versions. I am cross-building for armv7hf. This is my Dockerfile:

```
FROM resin/armv7hf-debian AS builder
RUN apt-get update \
    && apt-get install -yq --no-install-recommends build-essential automake
WORKDIR /tmp
ARG SPI_TOOLS_COMMIT=318bcae5249722873bf58b27afdd20473c7047cc
ADD https://github.com/cpb-/spi-tools/archive/${SPI_TOOLS_COMMIT}.tar.gz .
RUN tar xf ${SPI_TOOLS_COMMIT}.tar.gz \
    && cd spi-tools-${SPI_TOOLS_COMMIT} \
    && autoreconf -fim \
    && ./configure -q --prefix=/ \
    && make install

FROM resin/armv7hf-debian
COPY --from=builder /bin/spi-config /bin/spi-pipe /usr/bin/
COPY app /app
CMD /app/start.sh
```

I call the build command like this:
```
$ DEBUG=1 resin build --logs --emulated --application MyApp --projectName MyProject
```
This is the output I get:
```
[Debug]   Parsing input...
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   Failed to resolve project: 
[Debug]   AggregateError of:
[Debug]       Error: ENOENT: no such file or directory, open '****/resin-compose.yml'
[Debug]       Error: ENOENT: no such file or directory, open '****/resin-compose.yaml'
[Debug]       Error: ENOENT: no such file or directory, open '****/docker-compose.yml'
[Debug]       Error: ENOENT: no such file or directory, open '****/docker-compose.yaml'
[Info]    Creating default composition with source: ****
[Debug]   Creating project...
[Info]    Building for armv7hf/hummingboard
[Build]   Building services...
[Build]   main          Preparing...
[Info]    Installing qemu for ARM emulation...
[Info]    Emulation is enabled
[Debug]   Prepared tasks; building...
[Build]   main          Step 1/13 : FROM resin/armv7hf-debian AS builder
[Build]   main           ---> af9c05457784
[Build]   main          Step 2/13 : COPY [".resin/qemu-execve","/tmp/qemu-execve"]
[Build]   main           ---> Using cache
[Build]   main           ---> afbcc5c84cb9
[Build]   main          Step 3/13 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","apt-get update && apt-get install -yq --no-install-recommends     build-essential     automake"]
[Build]   main           ---> Using cache
[Build]   main           ---> e0aca16a992a
[Build]   main          Step 4/13 : WORKDIR /tmp
[Build]   main           ---> Using cache
[Build]   main           ---> ea2d9e1e93fb
[Build]   main          Step 5/13 : ARG SPI_TOOLS_COMMIT=318bcae5249722873bf58b27afdd20473c7047cc
[Build]   main           ---> Using cache
[Build]   main           ---> 379505d391fb
[Build]   main          Step 6/13 : ADD ["https://github.com/cpb-/spi-tools/archive/${SPI_TOOLS_COMMIT}.tar.gz","."]
[Build]   main           ---> Using cache
[Build]   main           ---> 444d7158dd2e
[Build]   main          Step 7/13 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","tar xf ${SPI_TOOLS_COMMIT}.tar.gz     && cd spi-tools-${SPI_TOOLS_COMMIT}     && autoreconf -fim     && ./configure -q --prefix=/     && make install"]
[Build]   main           ---> Using cache
[Build]   main           ---> a09ccd12f0f8
[Build]   main          Step 8/13 : FROM resin/armv7hf-debian
[Build]   main           ---> af9c05457784
[Build]   main          Step 9/13 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","apt-get update && apt-get install -yq --no-install-recommends     dbus     curl     && apt-get clean && rm -rf /var/lib/apt/lists/*"]
[Build]   main           ---> Running in bdefd3c8b247
[Build]   Built 1 service in 0:08
[Error]   Build failed
Error: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/tmp/qemu-execve\": stat /tmp/qemu-execve: no such file or directory": unknown
    at Stream.<anonymous> (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/resin-docker-build/build/builder.js:69:33)
    at Stream.stream.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at Stream.emit (events.js:160:13)
    at drain (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:646:20)
    at IncomingMessage.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at IncomingMessage.Readable.push (_stream_readable.js:213:10)
    at HTTPParser.parserOnBody (_http_common.js:130:22)
    at Socket.socketOnData (_http_client.js:439:20)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onread (net.js:602:20)
```

### PR DESCRIPTION
**Pull request by pimterry**
Quick update to pull in the fix from https://github.com/resin-io-modules/docker-qemu-transpose/pull/15

Fixes #814
Change-Type: patch

### CODE REVIEW

**Comment by thgreasi** [comment]
Don't wan't to raise unnecessary concerns but just as a heads-up, while trying this on the dockerfile from the associated issue at some point I got:
```
[Build]   Built 1 service in 9:10
[Error]   Build failed
COPY failed: stat /var/lib/docker/tmp/docker-builder398251528/--from=builder: no such file or directory
```

**Comment by CameronDiver** [comment]
@thgreasi that looks like it may be another issue with copy commands, looking into it now.

**Comment by CameronDiver** [comment]
Confirmed that this is a seperate issue with docker-qemu-transpose, we just never saw it because it was hidden with the last error. Fixing now, we might as well wait for the next version bump before merging this @pimterry

**Comment by CameronDiver** [comment]
@pimterry docker-qemu-transpose@v0.4.1 release which fixes the above issue.

**Comment by pimterry** [comment]
Perfect! Great find @thgreasi, great fix @CameronDiver. I've now bumped to 0.4.1 - I'll merge & ship once the tests pass.

**Pull request merged**
