### PR TITLE
add bash completions

### PR DESCRIPTION
**Pull request by mccollam**
This contains bash completion functionality for the resin CLI, including completion for sub-commands.

(These would normally be installed in /etc/bash_completion.d/ or ~/.bash_completion but I'm not sure how installing to those locations works within npm, sorry)

### CODE REVIEW

**Comment by mccollam** [comment]
Good idea; I've updated the README with more info.

**Comment by pimterry** [comment]
@mccollam this should pass if you rebase on master now.

**Comment by pimterry** [comment]
I've gone ahead and rebased - I'll merge in a sec once the tests have passed.

**Comment by mccollam** [comment]
(Sorry Tim, I missed the rebase request earlier!)

**Pull request merged**
