### PR TITLE
Show device dashboard url in 'resin device' output

### PR DESCRIPTION
**Pull request by lekkas**
Important Note: this should be merged after https://github.com/resin-io/resin-sdk/pull/226 has been merged and published.

Connects to #395

### CODE REVIEW

**Comment by lekkas** [comment]
Hey @emirotin , sorry I missed this ping, yeah I also still think it's a nice little improvement.

This depends on https://github.com/resin-io/resin-sdk/pull/226 which was blocked for a while due to failing sdk tests. I'll rebase the sdk PR since it's gone stale and push this forward again

**Comment by lekkas** [comment]
@emirotin I've updated the [SDK PR](https://github.com/resin-io/resin-sdk/pull/226), but I can see that all open PRs are marked as having their CI tests failing. What is the current state of things with regards to SDK testing? I guess I shouldn't expect the CI tests to go green right?

**Comment by emirotin** [comment]
Well, they should pass most of the times. 
For example the tests here https://travis-ci.org/resin-io/resin-sdk/jobs/223362503 fail because the API part is not deployed.
So normally you _should_ expect your tests to become green.

**Comment by lekkas** [comment]
Got it, my PR was correctly failing the tests due to a bug in my code, I'm fixing it and will ping you again for review when it passes the tests.

**Comment by lekkas** [comment]
https://github.com/resin-io/resin-sdk/pull/226 has landed in `resin-sdk@6.2.0`, it will be picked up by `resin-sdk-preconfigured` in new `resin-cli` installations (or by simply reinstalling it) , so I'm merging this cc @emirotin @pimterry

**Pull request merged**
