### PR TITLE
Use _.fromPairs instead of _.object which was removed in lodash 4.0.0

### PR DESCRIPTION
**Pull request by zvin**
Connects-To: #636

Change-Type: patch

### CODE REVIEW

**Comment by zvin** [comment]
@emirotin @pimterry any idea what might be wrong with the travis build ?

**Comment by emirotin** [comment]
Super-strange and reproducible. No idea wtf

**Comment by pimterry** [comment]
@zvin the travis problem is that it can't find `.travis.yml`, so it's trying to build it as a default ruby project, which obviously isn't going to work. If you rebase on top of master you'll pick up the `.travis.yml`, and that'll fix it.

**Comment by pimterry** [comment]
It'd be good to merge this and get a 6.5.1 fixed release out as soon as we can - in the mean time I've reset `latest` on npm to 6.4.0, so new installs won't pick up the release with this bug in it by default.

**Pull request merged**
